services:
  product-service:
    build:
      context: ./ProductService
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionStrings__DeffaultConnection=Server=localhost;Database=ProductDb;User Id=sa;Password=<PWunitek$>;Encrypt=False;
      - ConnectionStrings__DeffaultConnection=Server=host.docker.internal;Database=ProductDb;User Id=sa;Password=TUCLAVE;Encrypt=False;
  order-service:
    build:
      context: ./OrderService
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionStrings__DeffaultConnection=Server=localhost;Database=ProductDb;User Id=sa;Password=<PWunitek$>;Encrypt=False;
      - ConnectionStrings__DeffaultConnection=Server=host.docker.internal;Database=OrderDb;User Id=sa;Password=TUCLAVE;Encrypt=False;